FROM bash

LABEL version="1.0.0"
LABEL repository="http://github.com/toolmantim/actions/hello-world"
LABEL homepage="http://github.com/toolmantim/actions/hello-world"
LABEL maintainer="Tim Lucas <t@toolmantim.com>"

LABEL com.github.actions.name="Hello World"
LABEL com.github.actions.description="Prints a hello world."
LABEL com.github.actions.icon="zap"
LABEL com.github.actions.color="blue"

ENTRYPOINT ["bash", "-c", "echo 'Hello GitHub Actions!'"]